### ISSUE TITLE
Same instance of Presenter injected in all instances of a class

### ISSUE THREAD

**Issue by RiccardoM** [6thsolution/EasyMVP#28]
**Problem**
I've encountered a pretty big bug (or maybe not-thought feature?).  
Let's say we have the following presenter class:
```java
public class Presenter extends AbstractPresenter<View> {
    private static int counter = 0;
    private int count = counter++;

    public void setupView(){
        getView().setLabelText(String.valueOf(count));
    }

}
```
Which is used by the following view class:
``` java
@CustomView(presenter = Presenter.class)
public class ViewImpl extends android.View implements View {
    @Presenter Presenter presenter;
    @BindView(R2.id.icon_label_textview) TextView labelTextView;

    public ViewImpl(Context context){
        View view = LayoutInflater.from(context).inflate(R.layout.view_layout, this);
        ButterKnife.bind(this, view);
    }

    @Override
    protected void onAttachedToWindow() {
        super.onAttachedToWindow();
        presenter.setupView();
    }

    @Override
    public void setLabelText(String text) {
        labelTextView.setText(text);
    }
```
That implements the followin interface:
``` java
public interface IconView {
    void setLabelText(String text);
```

Now, inside another class (let's say a fragment), we exceute the following piece of code:
``` java
for (int i = 0 ; i < 10; i ++){
   View view = new View(getActivity());  // Create a new View instance
   addView(view);  // Adds the view to the layout
}
```

What will happen is that the first `View` that gets created triggers the `Presenter` creation, and thus will correctly show a label displaying the number `0` (initial value of `counter`). But then, starting from the second icon onwards, the `Presenter` instances associated with the new `View` instances will all refer the first `Presenter` instance, thus showing other 9 labels all with the value `0` instead of the supposed increasing  `1`, `2`, `3`, ..., `9`.  
  
**Solution**
I think that this issue might be solved by adding a field to the `@Presenter` annotation, let's call it `refresh` which, if set to `true` performs the injection each time that a new instance of the class referring that field is created, otherwise it will remain all the same. Let's have a look at how it could be used in both cases:
```java
@CustomView(presenter = Presenter.class)
public class ViewImpl implements View{
    @Presenter(refresh = true) // This instance will be re-injected each time that a ViewImpl istance gets created
    Presenter presenter;
    
    ...
}
```
```java
@CustomView(presenter = Presenter.class)
public class ViewImpl implements View{
    // @Presenter(refresh = false) if the same of writing @Presenter, false is the default value
    @Presenter(refresh = false) // This instance will not be re-injected each time that a ViewImpl istance gets created
    Presenter presenter;
    
    ...
}
```

**Comment by mohamad-amin** [comment]
@RiccardoM I don't think it's a bug. Take a look at  [this gist](https://gist.github.com/mohamad-amin/3ad1f1cab0030c3644a9c244cafeda7b). This behavior is expected as you're using the `static` keyword. EasyMVP is creating multiple presenters but they all have the same pointer to the `counter` variable.
Does your presenter still show numbers from 0 to 9 if you remove the `static` keyword?

**Comment by RiccardoM** [comment]
@mohamad-amin The problem that I've described is that, instead of the **correct** `0 1 2 3 4 5 6 7 8 9` string, the code that I've presented prints the **incorrect** `0 0 0 0 0 0 0 0 0 0`. This is possibile **if and only if** the injected presenter instance if always the first that is created, otherwise it would correctly print `0 1 2 3 4 5 6 7 8 9` if the injection would perform as expected.

**Comment by RiccardoM** [comment]
Any progress on this @SaeedMasoumi?

**Comment by SaeedMasoumi** [comment]
@RiccardoM Sorry for responding too late. I found the problem, It's because your custom views has same `Loader` id so android give you same presenter instance.
I'm working on it to fix this problem

**Comment by RiccardoM** [comment]
@SaeedMasoumi Thanks man, appreciate it a lot.

**Comment by RiccardoM** [comment]
@SaeedMasoumi Any update on this?

**Comment by SaeedMasoumi** [comment]
@RiccardoM Sorry for late response,
I fixed this issue with [`@PresenterId`](https://github.com/6thsolution/EasyMVP/blob/master/easymvp-api/src/main/java/easymvp/annotation/PresenterId.java) annotation. Actually I can't found any better solution according to the limitation of android loaders.
So your `ViewImp` class should change to
```java
@CustomView(presenter = Presenter.class)
public class ViewImpl extends android.View implements View {
    @Presenter Presenter presenter;
    @BindView(R2.id.icon_label_textview) TextView labelTextView;

    @PresenterId
    int id = 0;

    public ViewImpl(Context context, int id){  // or any way you can fill "id"
        View view = LayoutInflater.from(context).inflate(R.layout.view_layout, this);
        ButterKnife.bind(this, view);
        this.id = id;
    }

    @Override
    protected void onAttachedToWindow() {
        super.onAttachedToWindow();
        presenter.setupView();
    }

    @Override
    public void setLabelText(String text) {
        labelTextView.setText(text);
    }
```
See this [test case](https://github.com/6thsolution/EasyMVP/blob/master/easymvp-test/src/main/java/com/sixthsolution/easymvp/test/AppCompatActivityWithMultiViews.java) for more info

**Comment by SaeedMasoumi** [comment]
Also this bug fix will be included in **1.2.0-beta5** release

**Comment by RiccardoM** [comment]
@SaeedMasoumi I guess it's fair as long as it solves the problem that many have encoutered. If, looking trough the code on how you made this happen, I find a better solution, I'll post it here just so later viewers can see it.  
I also think that this new annotation should be inserted into the README.md file to let everyone know its existence.

Thank you again, great job.

**Comment by SaeedMasoumi** [comment]
@RiccardoM Thanks, EasyMVP calls `getLoaderManager().initLoader(ID, ... , ... );
`method, by default the ID is a [simple counter object](https://github.com/6thsolution/EasyMVP/blob/master/easymvp-compiler/src/main/java/easymvp/compiler/generator/decorator/BaseDecorator.java#L126) so when you create multiple instances of a class it will assign same id to them, There will be better solutions maybe, I think it can be simplified with putting ids in `Bundle`, but i encountered some bugs in custom `View`s

**Comment by RiccardoM** [comment]
@SaeedMasoumi I checked this issue, and I saw that this is not solved when using Dagger to injecting the presenter issue. Could you give a check and confirm this?
